### ISSUE TITLE
Error: Could not find or load main class is.iclt.icenlp.runner.RunIceTagger while trying to Tag a text

### ISSUE THREAD

**Issue by roynirmal** [hrafnl/icenlp#1]
As the title suggets, I am getting this error whenever I am trying to execute the .\icetagger.bat file.

I have cloned your repository and run  .\icetagger.bat -i tag.txt -o tagged.out inside .\bat\icetagger

Running it inside windows powershell! 
Similar problem exists when I am trying to tokenize

**Comment by hrafnl** [comment]
If you clone the repo, you need to build it.  I assume that you indeed just want to run the tagger (as opposed to be able to change the code).  In that case, just download a release (pre-built executables): https://github.com/hrafnl/icenlp/releases
